config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/welcome', to: 'home#index'
  root to: "home#index"
  resources :people
  # get 'people/new', to: 'people#new'
  # post 'people', to: 'people#create'
  # get 'people/:id', to: 'people#show'
  # get 'people/:id/edit', to: 'people#edit'
  # patch 'people/:id', to: 'people#update', as: :person
  # delete 'people/:id', to: 'people#destroy'
  # get 'people', to: 'people#index'
  # get 'people/new', to: 'people#new', as: :new_people
  get 'people/user/:user_id', to: 'people#from_author'
  get 'start_evaluation', to: 'people#start_evaluation'
  post 'start_evaluation', to: 'people#start_evaluation'
  post 'evaluation', to: 'people#evaluation'
  post 'questions_evaluation', to: 'people#questions_evaluation'
end

app/models/person.rb
class Person < ApplicationRecord
    belongs_to :user 
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
    @@question_operation = [
        {"id": 1, "category": "Compromiso Organizacional", "question": "Trata de adaptarse a la organización."},
        {"id": 2, "category": "Compromiso Organizacional", "question": "Muestra lealtad y apego a aspectos críticos de la organización."},
        {"id": 3, "category": "Compromiso Organizacional", "question": "Expresa orgullo por la empresa promoviendo los valores de la misma al interior y al exterior."},
        {"id": 4, "category": "Pensamiento Analítico", "question": "Comprende situaciones y entiende aspectos básicos, analiza los problemas identificando las causas- efectos de los mismos."},
        {"id": 5, "category": "Pensamiento Analítico", "question": "Utiliza herramientas de análisis para identificar las causas de los problemas (Excel, diagramas)"},
        {"id": 6, "category": "Pensamiento Analítico", "question": "Identifica los temas clave para dar solución desde la causa raíz."},
        {"id": 7, "category": "Desarrollo de relaciones", "question": "Desarrolla relaciones de colaboración y confianza con personas de su equipo y de otras áreas buscando la colaboración."},
        {"id": 8, "category": "Desarrollo de relaciones", "question": "Desarrolla relaciones de largo plazo con su equipo de trabajo y si fuere el caso, con clientes, colaboradores externos y proveedores de confianza en beneficio de la empresa"},
        {"id": 9, "category": "Desarrollo de relaciones", "question": "Se relaciona con personal clave para el mejoramiento continuo (interno y externo) a partir de relaciones de confianza."},
        {"id": 10, "category": "Pro actividad/iniciativa", "question": "Actúa con sentido de urgencia y no espera que el problema se resuelva solo."},
        {"id": 11, "category": "Pro actividad/iniciativa", "question": "Define las acciones correctivas necesarias para evitar o atenuar los riesgos identificados que pudieran convertirse en problemas más graves."},
        {"id": 12, "category": "Pro actividad/iniciativa", "question": "Se anticipa y toma acción para evitar problemas al desarrollar planes y estrategias para evitar crisis futuras."},
        {"id": 13, "category": "Impacto e influencia", "question": "Utiliza múltiples medios para comunicarse, ajusta su lenguaje, estilo y estrategia de comunicación de acuerdo con las características y necesidades de las personas."},
        {"id": 14, "category": "Impacto e influencia", "question": "Apela a la razón, con datos e información de interés para comunicarse eficientemente con otras personas."},
        {"id": 15, "category": "Impacto e influencia", "question": "Identifica las reacciones de las otras personas y ajusta sus mensajes para influir positivamente."},
    ]
    @@question_operation_engineer = [
        {"id": 1, "category": "Compromiso Organizacional",
            "question": "Trata de adaptarse a la organización."},
        {"id": 2, "category": "Compromiso Organizacional",
            "question": "Muestra lealtad y apego a aspectos críticos de la organización."},
        {"id": 3, "category": "Compromiso Organizacional",
            "question": "Expresa orgullo por la empresa promoviendo los valores de la misma al interior y al exterior."},
        {"id": 4, "category": "Aprendizaje Continuo",
            "question": "Realiza un gran esfuerzo por adquirir nuevas habilidades. Toma cursos y aplica sus conocimientos en los ciclos."},
        {"id": 5, "category": "Aprendizaje Continuo",
            "question": "Mantiene su formación técnica actualizada, busca información relevante, lee libros, blogs o escucha algun podcast."},
        {"id": 6, "category": "Aprendizaje Continuo",
            "question": "Comparte sus conocimientos y experiencia actuando como propagador de nuevas tecnologías y como apoyo en la resolución de problemas de otros equipos."},
        {"id": 7, "category": "Desarrollo de relaciones",
            "question": "Desarrolla relaciones de colaboración y confianza con personas de su equipo y de otras áreas buscando la colaboración."},
        {"id": 8, "category": "Desarrollo de relaciones",
            "question": "Desarrolla relaciones de largo plazo, y si fuere el caso tambien lo haría con colaboradores externos y proveedores en beneficio de la empresa."},
        {"id": 9, "category": "Desarrollo de relaciones",
            "question": "Se relaciona a partir de una comunicación empática y transparente, buscando entender a su contraparte antes de ser entendido."},
        {"id": 10, "category": "Pro actividad/iniciativa",
            "question": "Actúa con sentido de urgencia y no espera que el problema se resuelva solo."},
        {"id": 11, "category": "Pro actividad/iniciativa",
            "question": "Define las acciones correctivas necesarias para evitar o atenuar los riesgos identificados que pudieran convertirse en problemas más graves."},
        {"id": 12, "category": "Pro actividad/iniciativa",
            "question": "Se anticipa y toma acción para evitar problemas al desarrollar planes y estrategias para evitar crisis futuras."},
        {"id": 13, "category": "Impacto e influencia",
            "question": "Utiliza múltiples medios para comunicarse, ajusta su lenguaje, estilo y estrategia de comunicación de acuerdo con las características y necesidades de las personas."},
        {"id": 14, "category": "Impacto e influencia",
            "question": "Apela a la razón, con datos e información de interés para comunicarse eficientemente con otras personas."},
        {"id": 15, "category": "Impacto e influencia",
            "question": "Identifica las reacciones de las otras personas y ajusta sus mensajes para influir positivamente."},
    ]
    @@question_strategist = [
        {"id": 1, "category": "Compromiso Organizacional", "question": "Realiza esfuerzos adicionales para apoyar la misión y valores organizacionales."},
        {"id": 2, "category": "Compromiso Organizacional", "question": "Se esfuerza por actuar de acuerdo con los lineamientos de la alta dirección en cuanto a la misión y valores organizacionales."},
        {"id": 3, "category": "Compromiso Organizacional", "question": "Apoya las decisiones que benefician a la organización aun cuando no sean populares."},
        {"id": 4, "category": "Pensamiento Analítico", "question": "Analiza problemas identificando distintas relaciones entre diversas causas apoyándose con herramientas de análisis de datos."},
        {"id": 5, "category": "Pensamiento Analítico", "question": "Reconoce patrones en problemas frecuentes identificando la solución más eficiente."},
        {"id": 6, "category": "Pensamiento Analítico", "question": "Utiliza herramientas de análisis para identificar las causas de los problemas (Excel, diagramas)."},
        {"id": 7, "category": "Liderazgo de Equipo", "question": "Promueve la efectividad del equipo, establece límites para el desempeño y genera condiciones para que el equipo desempeñe su trabajo de la mejor manera."},
        {"id": 8, "category": "Liderazgo de Equipo", "question": "Es un líder de confianza, se posiciona como modelo a seguir impulsando continuamente el desarrollo de su equipo."},
        {"id": 9, "category": "Liderazgo de Equipo", "question": "Es un líder que genera entusiasmo y compromiso guiando continuamente al personal hacia los objetivos de la empresa."},
        {"id": 10, "category": "Desarrollo de otros", "question": "Identifica las áreas de oportunidad de las personas de su equipo y los motiva en su desarrollo, brindando herramientas que pueda tener a su alcance."},
        {"id": 11, "category": "Desarrollo de otros", "question": "Desarrolla al personal a partir de sesiones de retroalimentación o capacitación específica"},
        {"id": 12, "category": "Desarrollo de otros", "question": "Desarrolla al personal a partir de asignaciones en proyectos que representen un reto."},
        {"id": 13, "category": "Desarrollo de Relaciones", "question": "Desarrolla relaciones de colaboración y confianza con personas de su equipo y de otras áreas buscando la colaboración."},
        {"id": 14, "category": "Desarrollo de Relaciones", "question": "Desarrolla relaciones de largo plazo y si fuere el caso, con clientes, colaboradores externos y proveedores de confianza en beneficio de la empresa."},
        {"id": 15, "category": "Desarrollo de Relaciones", "question": "Se relaciona con personal clave para el mejoramiento continuo (interno y externo) a partir de una comunicación empática y transparente, buscando entender a su contraparte antes de ser entendido."},
    ]
    @@question_strategist_engineer = [
        {"id": 1, "category": "Compromiso Organizacional", "question": "Realiza esfuerzos adicionales para apoyar la misión y valores organizacionales."},
        {"id": 2, "category": "Compromiso Organizacional", "question": "Se esfuerza por actuar de acuerdo con los lineamientos de la alta dirección en cuanto a la misión y valores organizacionales."},
        {"id": 3, "category": "Compromiso Organizacional", "question": "Apoya las decisiones que benefician a la organización aun cuando no sean populares."},
        {"id": 4, "category": "Aprendizaje Continuo", "question": "Realiza un gran esfuerzo por adquirir nuevas habilidades. Toma cursos y aplica sus conocimientos en los ciclos."},
        {"id": 5, "category": "Aprendizaje Continuo", "question": "Mantiene su formación técnica actualizada, busca información relevante, lee libros, blogs o escucha algun podcast."},
        {"id": 6, "category": "Aprendizaje Continuo", "question": "Comparte sus conocimientos y experiencia actuando como propagador de nuevas tecnologías y como apoyo en la resolución de problemas de otros equipos."},
        {"id": 7, "category": "Liderazgo de Equipo", "question": "Promueve la efectividad del equipo, establece límites para el desempeño y genera condiciones para que el equipo desempeñe su trabajo de la mejor manera."},

app/helpers/people_helper.rb
module PeopleHelper
end

app/views/people/_form.html.erb
<div class='container'>
<%= form_with(model: @person, local: true) do |form| %>
    <div class="field">
        <%=form.label :name %>
        <%=form.text_field :name %>
    </div>
    <div class="field">
        <%=form.label :category %>
        <%=form.text_field :category %>
    </div>
    <div class="field">
        <%=form.label :email %>
        <%=form.text_field :email %>
    </div>
    <div class="field">
        <%=form.label :area %>
        <%=form.text_field :area %>
    </div>
    <div class="field">
        <%=form.label :leader %>
        <%=form.text_field :leader %>
    </div>
    <div class="mt-3 d-flex justify-content-center">
        <%=form.submit :Add, class: 'col-2 btn btn-primary' %>
    </div>
<% end %>
</div>

app/views/people/_person.html.erb
<div class='card padding margin-top'>
    <h3 class='text-uppercase'> <%= person.name %> </h3>
    <p class='text-secondary'>  <%=person.created_at %> </p>
    <%= link_to 'Ver más', person %>
</div>

app/views/people/_questions.html.erb
<% if question[:id] == 1 || (question[:id]+2) % 3 == 0%>
    <br>
    <h4 class="title-category" style="color: #ef4f4f;"> <%=question[:category]%> </h4>
<% end %>
<h5 class=""><%= question[:id] %>.- <%= question[:question] %></h5>
<div class="mb-2 d-flex justify-content-around flex-wrap">
    <table>
        <tr class="row justify-content-between">
            <td class="align-middle col-2 text-center">Totalmente en Desacuerdo</td>
            <td class="align-middle col-2 text-center">En desacuerdo</td>
            <td class="align-middle col-2 text-center">Neutro</td>
            <td class="align-middle col-2 text-center">De acuerdo</td>
            <td class="align-middle col-2 text-center">Totalmente de acuerdo</td>
        </tr>
        <tr class="row justify-content-between">
            <!-- <td class="col-2 text-center"><input type="radio" id=question[:id].to_s name=<%"a"+question[:id].to_s%> value="0" ></td> -->
            <!-- <td class="col-2 text-center"><input type="radio" id=question[:id].to_s name=<%"a"+question[:id].to_s%> value="1" ></td> -->
            <!-- <td class="col-2 text-center"><input type="radio" id=question[:id].to_s name=<%"a"+question[:id].to_s%> value="2" ></td> -->
            <!-- <td class="col-2 text-center"><input type="radio" id=question[:id].to_s name=<%"a"+question[:id].to_s%> value="3" ></td> -->
            <!-- <td class="col-2 text-center"><input type="radio" id=question[:id].to_s name=<%"a"+question[:id].to_s%> value="4" ></td> -->
            
            <td class="col-2 text-center"><%= radio_button_tag("a"+question[:id].to_s, 0) %></td> 
            <td class="col-2 text-center"><%= radio_button_tag("a"+question[:id].to_s, 1) %></td> 
            <td class="col-2 text-center"><%= radio_button_tag("a"+question[:id].to_s, 2, checked = false, required: true) %></td> 
            <td class="col-2 text-center"><%= radio_button_tag("a"+question[:id].to_s, 3) %></td> 
            <td class="col-2 text-center"><%= radio_button_tag("a"+question[:id].to_s, 4) %></td> 
            
        </tr>
    </table>
</div>

app/views/people/edit.html.erb
<div class='small-container center-block '>
  <%= render 'people/form' %>
</div>

app/views/people/evaluation.html.erb
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script>
  $(document).ready(function () {
    $("#name-person").hide()
  });
</script>
  
<div class="container mt-5 mb-5">
    <% if @name_evaluator %>
    <h3 class="text-center mb-4">Evaluación de <%=@name_evaluated%>, por <%=@name_evaluator%> </h3>
    <% else %>
    <h3 class="text-center mb-4">Evaluación de <%=@name_evaluated%>, por <%=current_user.email%> </h3>
    <% end %>
    <h4>Las siguientes preguntas están divididas en categorías que ayudan a evaluar el
performance del equipo de Reservamos.</h4>
    <div class='container d-flex justify-content-center'>
    <form action="start_evaluation" method="POST" class="form-signin mt-3 col-12 register-login-input">
        <fieldset>
            <% if @personArea == "engineer" %>
                <% if @personCategory == "Operation" %>
                    <% @questions_operation_engineer.each do |question| %>
                        <%= render 'questions', {question: question} %>
                    <% end %>
                    <br>
                <% end %>
                <% if @personCategory == "Strategist" %>
                    <% @questions_strategist_engineer.each do |question| %>
                        <%= render 'questions', {question: question} %>
                    <% end %>
                    <br>
                <% end %>
                <% if @personCategory == "Direction" %>
                    <% @questions_management_engineer.each do |question| %>
                        <%= render 'questions', {question: question} %>
                    <% end %>
                    <br>
                <% end %>
                <% if @name_evaluator == @personLeader  %>
                    <div class="mt-2">
                        <h5>Evaluación por Ciclos</h5>
                        <p> Ingresa la evaluación de cada ciclo hasta la fecha de la persona evaluada.
                        Si el ciclo no ha sido evaluado deja <b>vacío</b> el espacio.
                        </p>
                        <table>
                            <tr class="container row justify-content-around">
                                <td class="col-5">
                                <label for="C1">C1:</label>
                                <input class="col-8" type="number" step="any" id="C1" name="C1" placeholder="--" required>%
                                </td>
                                <td class="col-5"><label for="C2">C2:</label>
                                <input class="col-8" type="number" step="any" id="C2" name="C2" placeholder="--" required>%
                                </td>
                                <td class="col-5"><label for="C3">C3:</label>
                                <input class="col-8" type="number" step="any" id="C3" name="C3" placeholder="--" required>%
                                </td>
                                <td class="col-5"><label for="C4">C4:</label>
                                <input class="col-8" type="number" step="any" id="C4" name="C4" placeholder="--" required>%
                                </td>
                            </tr>
                            <tr class="container row justify-content-around">
                                <td class="col-5"><label for="C5">C5:</label>
                                <input class="col-8" type="number" step="any" id="C5" name="C5" placeholder="--">%
                                </td>
                                <td class="col-5"><label for="C6">C6:</label>
                                <input class="col-8" type="number" step="any" id="C6" name="C6" placeholder="--">%<br>
                                </td>
                                <td class="col-5"><label for="C7">C7:</label>
                                <input class="col-8" type="number" step="any" id="C7" name="C7" placeholder="--">%<br>
                                </td>
                                <td class="col-5"><label for="C8">C8:</label>
                                <input class="col-8" type="number" step="any" id="C8" name="C8" placeholder="--">%
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="mt-4">
                        <h5>Feedback para la persona evaluada </h5>
                        <div class="mb-3">
                            <label for="comment_1" class="form-label">Logros más destacados</label>
                            <textarea class="form-control form-control-sm" rows="3" name="comment_1" required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="comment_1" class="form-label">Recomendaciones</label>
                            <textarea class="form-control form-control-sm" rows="3" name="comment_2" required></textarea>
                        </div>
                    </div>
                <% end %>
            
            <% elsif @personArea != "engineer" %>
                <% if @personCategory == "Operation" %>
                    <% @questions_operation.each do |question| %>
                        <%= render 'questions', {question: question} %>
                    <% end %>
                    <br>
                <% end %>
                <% if @personCategory == "Strategist" %>
                    <% @questions_strategist.each do |question| %>
                        <%= render 'questions', {question: question} %>
                    <% end %>
                    <br>
                <% end %>
                <% if @personCategory == "Direction" %>
                    <% @questions_management.each do |question| %>
                        <%= render 'questions', {question: question} %>
                    <% end %>
                    <br>
                <% end %>
                <% if @name_evaluator == @personLeader  %>
                    <div class="mt-2">
                        <h5>Evaluación por Q's</h5>
                        <p> Ingresa la evaluación de cada Q hasta la fecha de la persona evaluada.
                        Si el Q no ha sido evaluado deja <b>vacío</b> el espacio.
                        </p>
                        <table>
                            <tr class="container row justify-content-around">
                                <td class="col-6"><label for="Q1">Q1:</label>
                                <input class="col-8" type="number" step="any" id="Q1" name="Q1" placeholder="--" required>%
                                </td>
                                <td class="col-6"><label for="Q2">Q2:</label>
                                <input class="col-8" type="number" step="any" id="Q2" name="Q2" placeholder="--" required>%
                                </td>
                                <td class="col-6"><label for="Q3">Q3:</label>
                                <input class="col-8" type="number" step="any" id="Q3" name="Q3" placeholder="--">%
                                </td>
                                <td class="col-6"><label for="Q4">Q4:</label>
                                <input class="col-8" type="number" step="any" id="Q4" name="Q4" placeholder="--">%
                                </td>
                            </tr>
                        </table>
                    </div>
                    <div class="mt-4">
                        <h5>Feedback para la persona evaluada </h5>
                        <div class="mb-3">
                            <label for="comment_1" class="form-label">Logros más destacados</label>
                            <textarea class="form-control form-control-sm" rows="3" name="comment_1" required></textarea>
                        </div>
                        <div class="mb-3">
                            <label for="comment_1" class="form-label">Recomendaciones</label>
                            <textarea class="form-control form-control-sm" rows="3" name="comment_2" required></textarea>
                        </div>
                    </div>
                <% end %>
            <% end %>
            <div class="text-center mt-4">
                <button type="submit" class="col-3 btn btn-primary text-center" id="send">Send</button>
            </div>
            <div id="name-person">
                <p> The evaluated person is: </p>
                <input name="name_person" value="<%=@name_evaluated%>" selected>
            </div>
        </fieldset>
    </form>
    </div>

</div>

app/views/people/from_author.html.erb
<div class='large-container center-block'>
  <h1> People created by <%= @user.email %> </h1>
  <%= render @user.people %>
</div>

app/views/people/index.html.erb
<div class='container center-block'>
    <h1>
        People
    </h1>
    
    <table class="table table-hover table-responsive col-12 text-center">
    <thead class="thead-dark">
        <tr>
        <th width="20%">Name</th>
        <th width="15%">Category</th>
        <th width="20%">Email</th>
        <th width="15%">Area</th>
        <th width="20%">Leader</th>
        <th width="10%">More</th>
        </tr>
    </thead>
    <% @people.each do |person| %>
        <tbody>
        <tr>
          <td width="20%"><%= person.name %></td>
          <td width="15%"><%= person.category %></td>
          <td width="20%"><%= person.email %></td>
          <td width="15%"><%= person.area %></td>
          <td width="20%"><%= person.leader %></td>
          <td width="10%"><%= link_to 'Ver más', person %>
        </tr>
      </tbody>
    <% end %>
    </table>
   
    <!-- <%= render @people %> -->
    <div class="d-flex justify-content-center mt-5 col-sm-4 center-block">
    <%= link_to 'Add Person', new_person_path, class: 'btn btn-primary' %>
    </div>
</div>

app/views/people/new.html.erb
<div class='small-container center-block '>
  <%= render 'people/form' %>
  <!-- <h1>A variable: <%=@newline%></h1> -->
</div>

app/views/people/show.html.erb
<div class='large-container center-block'>
    <h1>
        <%= @person.name %>
    </h1>
    <div>
        <%= @person.category %>
    </div>
    <div>
        <%= @person.email %>
    </div>
    <div>
        <%= @person.area %>
    </div>
    <div>
        <%= @person.leader %>
    </div>
    <div>
        <p> Added by: <strong><%= @person.user.email %></strong></p>
    </div>

    <div class="mb-3">
    <%= link_to 'Edit person', edit_person_path(@person), class: 'btn btn-primary mr-2 my-2 my-sm-0' %>
    </div>
    <div>
    <%= link_to 'Delete person', @person, method: :delete, class: 'btn btn-primary mr-2 my-2 my-sm-0' %>
    </div>
    
</div>

app/views/people/start_evaluation.html.erb
<div class="container mt-5">
    <% if true %>
      <h4 class="questions-title">Hola <%=@name_evaluator%>. Las siguientes preguntas están divididas en categorías que ayudan a evaluar el
        performance del equipo de Reservamos. </h4>
    <% else %>
      <h4 class="questions-title">Hola <%=current_user.email%>. Las siguientes preguntas están divididas en categorías que ayudan a evaluar el
        performance del equipo de Reservamos. </h4>
    <% end %>
    <div class='container d-flex justify-content-center text-center'>
    <form action="evaluation" method="POST" class="form-signin mt-3 col-6 register-login-input">
        <fieldset>
        <legend>Choose a person to start the evaluation</legend>
            <!-- <select class="form-control form-control-sm" name="name_person" id="name-select" onchange="javascript:this.form.submit()" required> -->
            <!-- <select class="form-control form-control-sm" name="name_person" id="name-select" onchange= "alert('hello')" required> -->
            <select class="form-control form-control-sm" name="name_person" id="name-select" onchange= "javascript:this.form.submit()" required>
            <option value=""> -- Please choose an option -- </option>
            <% @people.each do |individual| %>
            <option value="<%= individual.name %>"><%= individual.name %></option>
            <% end %>
            </select>
        </fieldset>
    </form>
    </div>
    <br>
</div>