config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get '/welcome', to: 'home#index'
  root to: "home#index"
  resources :people
  # get 'people/new', to: 'people#new'
  # post 'people', to: 'people#create'
  # get 'people/:id', to: 'people#show'
  # get 'people/:id/edit', to: 'people#edit'
  # patch 'people/:id', to: 'people#update', as: :person
  # delete 'people/:id', to: 'people#destroy'
  # get 'people', to: 'people#index'
  # get 'people/new', to: 'people#new', as: :new_people
  get 'people/user/:user_id', to: 'people#from_author'
  get 'start_evaluation', to: 'people#start_evaluation'
  post 'start_evaluation', to: 'people#start_evaluation'
  post 'evaluation', to: 'people#evaluation'
  post 'questions_evaluation', to: 'people#questions_evaluation'
end

app/views/partials/_nav.html.erb
<nav class="navbar navbar-default navbar-expand-lg fixed-top navbar-dark" style="background-color: purple;">
    <div class="container-fluid">
        <div class="navbar-header">
            <button type="button" class="navbar-toggler collapsed" 
            data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
            </button>
            <%= link_to root_path, class: "navbar-brand", id: "logo" do %>
                <%= image_tag("https://assets-fl.reservamos.mx/assets/logo-b09feb00a641615eb083fedea266d68ed48e1e46687e198437b7a1aab251860d.svg", :alt => "bus", class:"pt-1") %>
            <% end %>
            </div>
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><%= link_to 'Home', root_path, class: "nav-link active" %></li>
                <li><%= link_to 'Start Evaluation', start_evaluation_path, class: "nav-link active" %></li>
                <li><%= link_to 'People', people_path, class: "nav-link active" %></li>
                <% if user_signed_in? && current_user.email=='edith@reservamos.mx' %>
                    <li><%= link_to 'New Person', new_person_path, class: "nav-link active" %></li>
                <% end %>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <% if user_signed_in? %>
                    <%= link_to 'Log out', destroy_user_session_path, method: :delete, class: 'btn btn-primary nav-link active' %>
                <% else %>
                    <%= link_to 'Log in', new_user_session_path, class: 'btn btn-success mr-2 my-2 my-sm-0' %>
                    <%= link_to 'Register', new_user_registration_path, class: 'btn btn-primary mr-2 my-2 my-sm-0' %>
                <% end %>
            </ul>
        </div>
    </div>
</nav>